# Generated by Django 5.0.4 on 2024-04-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theory',
            options={'verbose_name': 'Теория', 'verbose_name_plural': 'Теория'},
        ),
        migrations.AlterField(
            model_name='theory',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
