# Generated by Django 5.0.4 on 2024-05-05 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blind', '0005_typingresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typingresult',
            name='text_template',
        ),
    ]
