# Generated by Django 5.0.4 on 2024-05-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blind', '0003_texttemplates_delete_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='texttemplates',
            options={'verbose_name': 'Текст', 'verbose_name_plural': 'Текста'},
        ),
    ]
