# Generated by Django 5.0.4 on 2024-05-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind', '0006_remove_typingresult_text_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typingresult',
            name='time_taken',
            field=models.IntegerField(),
        ),
    ]
