# Generated by Django 5.0.4 on 2024-05-08 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind', '0007_alter_typingresult_time_taken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='typingresult',
            name='accuracy',
            field=models.FloatField(default=0, verbose_name='Аккуратность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typingresult',
            name='print_speed',
            field=models.FloatField(default=0, verbose_name='Количество символов в минуту'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='texttemplates',
            name='character_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество символов'),
        ),
        migrations.AlterField(
            model_name='texttemplates',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='texttemplates',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='content',
            field=models.TextField(db_index=True, max_length=4096, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='date_of_publication',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='theory',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='typingresult',
            name='characters_typed',
            field=models.IntegerField(verbose_name='Количество символов'),
        ),
        migrations.AlterField(
            model_name='typingresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='typingresult',
            name='errors_count',
            field=models.IntegerField(verbose_name='Количество ошибок'),
        ),
        migrations.AlterField(
            model_name='typingresult',
            name='time_taken',
            field=models.IntegerField(verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='typingresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя'),
        ),
    ]
