# Generated by Django 5.0.4 on 2024-05-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind', '0009_alter_typingresult_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theory',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='theory',
            name='content',
            field=models.TextField(db_index=True, verbose_name='Текст'),
        ),
    ]
