# Generated by Django 5.0.4 on 2024-05-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind', '0010_theory_image_alter_theory_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theory',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
