# Generated by Django 5.0.4 on 2024-06-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blind', '0011_alter_theory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texttemplates',
            name='character_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество символов'),
        ),
    ]
